layout_spectrum: 0.9639183
typography_spectrum: 0.1057572
color:
  lightness: 0.5899715
  brandStrength: 0.8404256
  saturation: 0.8838862
  rhythmicContrast: 0.7302878
  brandColors:
    - '#014C9B'
    - '#010105'
    - '#F4D10F'
    - '#FF0102'
    - '#D176BC'
name: Periscopitaly
