layout_spectrum: 0.9639183
name: Periscopitaly
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
color:
  brandStrength: 0.8404256
  lightness: 0.5252951
  saturation: 0.7023609
  rhythmicContrast: 0.4865093
  brandColors:
    - '#014C9B'
    - '#010105'
    - '#F4D10F'
    - '#FF0102'
    - '#D176BC'
typography_spectrum: 0.1057572
